server:
 servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost/examinationdb
    username: chris
    password: Chris@24
  jpa:
    show_sql: true
    hibernate:
      ddl_auto: update
    properties:
      hibernate:
        format-sql: true
        
examination:
  api:
    numberOfExaminationQuestion: 3